import { NextResponse } from "next/server";
import { generateEducationalImage } from "../../../lib/generate-educational-image";
import { prisma } from "../../../lib/prisma";
import { getSession } from "../../../lib/auth";
import {reserveAiUse,releaseAiUse} from "../../../lib/ai-entitlement";

async function currentUser(){
 const s=await getSession(); if(!s?.id)return null;
 const u=await prisma.user.findUnique({where:{id:String(s.id)},select:{id:true,role:true,accountType:true,active:true,organizationId:true,schoolId:true}});
 return u?.active?u:null;
}
function outputText(data:any){
 if(typeof data?.output_text==="string")return data.output_text;
 return (data?.output||[]).flatMap((o:any)=>o.content||[]).filter((c:any)=>c.type==="output_text").map((c:any)=>c.text).join("");
}
export async function GET(){
 const u=await currentUser();if(!u)return NextResponse.json({error:"No autorizado"},{status:401});
 const where:any={academicYear:{year:2027}};
 if(u.role==="DOCENTE"){if(!u.schoolId)return NextResponse.json({error:"Usuario docente sin establecimiento"},{status:403});where.schoolId=u.schoolId;if(u.accountType!=="INDIVIDUAL")where.teachingAssignments={some:{teacherId:u.id}}}
 else if(u.role==="DIRECTOR"||u.role==="UTP"){if(!u.schoolId)return NextResponse.json({error:"Usuario sin establecimiento"},{status:403});where.schoolId=u.schoolId}
 else if(u.role==="SOSTENEDOR"){if(!u.organizationId)return NextResponse.json({error:"Usuario sin organización"},{status:403});where.school={organizationId:u.organizationId}};
 const courses=await prisma.course.findMany({where,include:{teachingAssignments:{where:u.role==="DOCENTE"?{teacherId:u.id}:{},select:{subject:true,teacherId:true}},academicYear:true},orderBy:{name:"asc"}});
 const objectives=await prisma.learningObjective.findMany({where:{OR:[{moduleLinks:{some:{module:{active:true}}}},{moduleLinks:{none:{}}}]},include:{moduleLinks:{include:{module:true}}},orderBy:[{level:"asc"},{subject:"asc"},{code:"asc"}]}); const tpModules=await prisma.curriculumModule.findMany({where:{active:true},include:{objectives:{include:{objective:true}},units:{where:{active:true},include:{objectives:{include:{objective:true}}},orderBy:{number:"asc"}}},orderBy:[{specialty:"asc"},{level:"asc"},{code:"asc"}]});
 const planningScope:any=u.role==="DOCENTE"?{userId:u.id}:u.role==="SOSTENEDOR"?{course:{school:{organizationId:u.organizationId}}}:u.role==="DIRECTOR"||u.role==="UTP"?{course:{schoolId:u.schoolId}}:{};const plannings=await prisma.planning.findMany({where:planningScope,include:{course:true,objectives:{include:{objective:true}},implementation:true},orderBy:{createdAt:"desc"},take:10});
 return NextResponse.json({courses,objectives,tpModules,plannings,aiReady:!!process.env.OPENAI_API_KEY,accountType:u.accountType});
}
export async function POST(req:Request){
 const u=await currentUser();if(!u)return NextResponse.json({error:"No autorizado"},{status:401});
if(!process.env.OPENAI_API_KEY){console.error("[ai-planning] OPENAI_API_KEY missing");return NextResponse.json({error:"OPENAI_API_KEY no configurada",stage:"configuration"},{status:503});}
 const b=await req.json();
 const course=await prisma.course.findUnique({where:{id:String(b.courseId||"")},include:{academicYear:true,teachingAssignments:true,school:true}});
 if(!course)return NextResponse.json({error:"Curso no encontrado"},{status:404});
 if(u.role==="SOSTENEDOR"&&course.school.organizationId!==u.organizationId)return NextResponse.json({error:"Curso no autorizado"},{status:403});if(u.accountType!=="INDIVIDUAL"&&(u.role==="DIRECTOR"||u.role==="UTP"||u.role==="DOCENTE")&&(!u.schoolId||course.schoolId!==u.schoolId))return NextResponse.json({error:"Curso no autorizado"},{status:403});if(u.accountType==="INDIVIDUAL"&&course.schoolId!==u.schoolId)return NextResponse.json({error:"Curso personal no autorizado"},{status:403});
 const subject=String(b.subject||"").trim();const moduleId=String(b.moduleId||"").trim();
 if(u.role==="DOCENTE"&&u.accountType!=="INDIVIDUAL"&&!course.teachingAssignments.some(a=>a.teacherId===u.id&&(a.subject===subject||!!moduleId)))return NextResponse.json({error:"No tienes esta asignación docente"},{status:403});
 const ids=Array.isArray(b.objectiveIds)?b.objectiveIds.map(String):[];
 const unitId=String(b.unitId||"").trim();let curriculumUnit:any=null;
 if(unitId){curriculumUnit=await prisma.curriculumUnit.findFirst({where:{id:unitId,active:true},include:{objectives:true}});if(!curriculumUnit)return NextResponse.json({error:"Unidad curricular no encontrada"},{status:400});if(curriculumUnit.level!==course.level||curriculumUnit.subject!==subject)return NextResponse.json({error:"La unidad curricular no corresponde al curso o asignatura seleccionada"},{status:400});/* La selección OA→unidad se valida en la interfaz cuando existe una asociación oficial. Para unidades cuya asociación MINEDUC aún está pendiente, permitimos OA oficiales de la misma asignatura/nivel sin inventar una vinculación oficial. */}
 const objectives=moduleId?await prisma.learningObjective.findMany({where:{id:{in:ids},moduleLinks:{some:{moduleId,module:{active:true}}}}}):await prisma.learningObjective.findMany({where:{id:{in:ids},level:course.level,subject}});
 if(!objectives.length)return NextResponse.json({error:"Selecciona al menos un OA oficial disponible"},{status:400});
 if(moduleId){const module=await prisma.curriculumModule.findFirst({where:{id:moduleId,active:true}});if(!module)return NextResponse.json({error:"Módulo TP oficial no encontrado"},{status:400});if(module.level!==course.level||course.track!=="TP")return NextResponse.json({error:"El módulo TP no corresponde al nivel o modalidad del curso"},{status:400});} const allowedDurations=["45 minutos","90 minutos","135 minutos","180 minutos"];const requestedDuration=String(b.duration||"90 minutos");const duration=allowedDurations.includes(requestedDuration)?requestedDuration:"90 minutos";const modality="Clase a clase";const instructions=String(b.instructions||"");const includeAdaptations=b.includeAdaptations===true;const adaptationContext=String(b.adaptationContext||"").trim();
 const adaptationInstruction=includeAdaptations?`Incluye adecuacionesCurriculares como array separado de DUA. Contexto entregado por el docente: ${adaptationContext||"sin contexto adicional"}. Propón ajustes de acceso, metodología, recursos, tiempo, participación o evaluación según corresponda. No inventes diagnósticos ni datos personales y no modifiques los OA oficiales.`:"No generes adecuaciones curriculares individualizadas; usa solo principios generales DUA.";const modeInstruction=`Genera una planificación detallada para UNA clase de ${duration}, organizada en inicio, desarrollo y cierre. La suma de los minutos de inicio, desarrollo y cierre debe corresponder aproximadamente a la duración seleccionada.`;
 const unitInstruction=curriculumUnit?` Unidad curricular seleccionada: Unidad ${curriculumUnit.number}, "${curriculumUnit.title}". Conserva esta referencia en el contexto pedagógico.`:""; const prompt=`Genera una planificación docente chilena en español. No inventes ni modifiques los OA entregados.${unitInstruction} ${adaptationInstruction} Curso: ${course.name}. Nivel: ${course.level}. Asignatura: ${subject}. Duración de referencia: ${duration}. Modalidad: ${modality}. ${modeInstruction} Referencias curriculares MINEDUC seleccionadas: ${objectives.map(o=>o.code+": "+o.text).join(" | ")}. Usa estas referencias para crear contenido pedagógico original; no inventes códigos OA ni atribuyas a MINEDUC textos generados por la IA. Indicaciones adicionales: ${instructions||"ninguna"}. Cuando una imagen aporte comprensión pedagógica, puedes proponer hasta 4 apoyos visuales en total, distribuidos entre inicio, desarrollo o cierre; no agregues imágenes solo como decoración. Devuelve SOLO JSON válido con estas claves: titulo, objetivoClase, indicadores (array), inicio, desarrollo, cierre, recursos (array), evaluacionFormativa, dua (array), adecuacionesCurriculares (array), evidencia, observaciones, sugerenciasVisuales (array de objetos con descripcion,ubicacion,propositoPedagogico), secuenciaClases (array, puede quedar vacío en Clase a clase), periodos (array, puede quedar vacío en Clase a clase o Por Unidad), propositoUnidad, propositoPeriodo, hitosAprendizaje. Los campos inicio/desarrollo/cierre deben ser objetos con minutos, actividadesDocente y actividadesEstudiantes.`;
 const entitlement=await reserveAiUse(u.id);if(!entitlement.ok)return NextResponse.json({error:entitlement.error,stage:"entitlement"},{status:402});let generationSucceeded=false;try{const ai=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Authorization":`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5.6-terra",input:prompt})});
 const raw=await ai.json();
 if(!ai.ok){console.error("[ai-planning] OpenAI error",{status:ai.status,model:process.env.OPENAI_MODEL||"gpt-5.6-terra",error:raw?.error});return NextResponse.json({error:"La IA no pudo generar la planificación",detail:raw?.error?.message||"Error OpenAI",stage:"openai",status:ai.status},{status:502});}
 let text=outputText(raw).trim().replace(/^\`\`\`json\s*/i,"").replace(/\`\`\`$/,"").trim();if(!text){console.error("[ai-planning] empty OpenAI output",{responseId:raw?.id,status:raw?.status,incomplete:raw?.incomplete_details});return NextResponse.json({error:"La IA no devolvió contenido para la planificación.",detail:raw?.incomplete_details?.reason||raw?.status||"Respuesta vacía",stage:"output"},{status:502})}let generated:any;
 try{generated=JSON.parse(text)}catch(e){console.error("[ai-planning] invalid JSON",{responseId:raw?.id,text:text.slice(0,500)});return NextResponse.json({error:"La IA respondió en un formato no válido. Intenta nuevamente.",stage:"json"},{status:502})}
 const moments=["inicio","desarrollo","cierre"] as const;
 const validMoments=moments.every(k=>generated?.[k]&&generated[k].minutos!==undefined&&String(generated[k].actividadesDocente||"").trim()&&String(generated[k].actividadesEstudiantes||"").trim());
 if(!validMoments){return NextResponse.json({error:"La IA no entregó una planificación completa con Inicio, Desarrollo y Cierre. Intenta nuevamente."},{status:502});} const includeImages=b.includeImages!==false;if(includeImages){const suggestions=Array.isArray(generated.sugerenciasVisuales)?generated.sugerenciasVisuales.slice(0,4):[];generated.ilustraciones=(await Promise.all(suggestions.map(async(v:any)=>{const description=typeof v==="string"?v:String(v?.descripcion||"").trim();if(!description)return null;const image=await generateEducationalImage(`Planificación escolar. Curso ${course.level}. Asignatura ${subject}. ${description}. Recurso educativo visual, claro, limpio y apropiado para la edad.`);return image?{descripcion:description,ubicacion:v?.ubicacion||"",propositoPedagogico:v?.propositoPedagogico||"",image}:null}))).filter(Boolean);}
 if(curriculumUnit){generated.curriculumUnit={id:curriculumUnit.id,number:curriculumUnit.number,title:curriculumUnit.title,level:curriculumUnit.level,subject:curriculumUnit.subject,source:curriculumUnit.source};} const planning=await prisma.planning.create({data:{title:String(generated.titulo||`Planificación ${subject} · ${course.name}`),track:course.track,content:generated,userId:u.id,courseId:course.id,academicYearId:course.academicYearId,objectives:{create:objectives.map(o=>({objectiveId:o.id}))}},include:{course:true,objectives:{include:{objective:true}},implementation:true}});
 generationSucceeded=true;return NextResponse.json({planning},{status:201});}catch(e){console.error("[ai-planning] unexpected generation error",e);return NextResponse.json({error:"Ocurrió un error inesperado al generar la planificación. Tu cupo IA no será descontado.",stage:"unexpected"},{status:500})}finally{if(entitlement.reserved&&!generationSucceeded)await releaseAiUse(u.id)}
}
