import { NextResponse } from "next/server";
import { prisma } from "../../../lib/prisma";
import { getSession } from "../../../lib/auth";
import {checkAiEntitlement,chargeAiUse} from "../../../lib/ai-entitlement";

async function currentUser(){const s=await getSession();if(!s?.id)return null;const u=await prisma.user.findUnique({where:{id:String(s.id)},select:{id:true,role:true,accountType:true,active:true,organizationId:true,schoolId:true}});return u?.active?u:null}
function outputText(data:any){if(typeof data?.output_text==="string")return data.output_text;return (data?.output||[]).flatMap((o:any)=>o.content||[]).filter((c:any)=>c.type==="output_text").map((c:any)=>c.text).join("")}
export async function GET(){
 const u=await currentUser();if(!u)return NextResponse.json({error:"No autorizado"},{status:401});
 const where:any={academicYear:{year:2027}};if(u.role==="DOCENTE"){if(!u.schoolId)return NextResponse.json({error:"Usuario docente sin establecimiento"},{status:403});where.schoolId=u.schoolId;if(u.accountType!=="INDIVIDUAL")where.teachingAssignments={some:{teacherId:u.id}}}else if(u.role==="DIRECTOR"||u.role==="UTP"){if(!u.schoolId)return NextResponse.json({error:"Usuario sin establecimiento"},{status:403});where.schoolId=u.schoolId}else if(u.role==="SOSTENEDOR"){if(!u.organizationId)return NextResponse.json({error:"Usuario sin organización"},{status:403});where.school={organizationId:u.organizationId}};
 const courses=await prisma.course.findMany({where,include:{teachingAssignments:{where:u.role==="DOCENTE"?{teacherId:u.id}:{},select:{subject:true,teacherId:true}},academicYear:true},orderBy:{name:"asc"}});
 const objectives=await prisma.learningObjective.findMany({include:{moduleLinks:{include:{module:true}}},orderBy:[{level:"asc"},{subject:"asc"},{code:"asc"}]}); const tpModules=await prisma.curriculumModule.findMany({where:{active:true},include:{objectives:{include:{objective:true}}},orderBy:[{specialty:"asc"},{level:"asc"},{code:"asc"}]});
 const assessmentScope:any=u.role==="DOCENTE"?{userId:u.id}:u.role==="SOSTENEDOR"?{course:{school:{organizationId:u.organizationId}}}:u.role==="DIRECTOR"||u.role==="UTP"?{course:{schoolId:u.schoolId}}:{};const assessments=await prisma.assessment.findMany({where:assessmentScope,include:{course:true,objectives:{include:{objective:true}},result:true},orderBy:{createdAt:"desc"},take:10});
 return NextResponse.json({courses,objectives,tpModules,assessments,aiReady:!!process.env.OPENAI_API_KEY});
}
export async function POST(req:Request){
 const u=await currentUser();if(!u)return NextResponse.json({error:"No autorizado"},{status:401});const entitlement=await checkAiEntitlement(u.id);if(!entitlement.ok)return NextResponse.json({error:entitlement.error},{status:402});if(!process.env.OPENAI_API_KEY)return NextResponse.json({error:"OPENAI_API_KEY no configurada"},{status:503});
 const b=await req.json();const course=await prisma.course.findUnique({where:{id:String(b.courseId||"")},include:{teachingAssignments:true,school:true}});if(!course)return NextResponse.json({error:"Curso no encontrado"},{status:404});
 if(u.role==="SOSTENEDOR"&&course.school.organizationId!==u.organizationId)return NextResponse.json({error:"Curso no autorizado"},{status:403});if((u.role==="DIRECTOR"||u.role==="UTP"||u.role==="DOCENTE")&&(!u.schoolId||course.schoolId!==u.schoolId))return NextResponse.json({error:"Curso no autorizado"},{status:403});
 const subject=String(b.subject||"").trim();if(u.role==="DOCENTE"&&!course.teachingAssignments.some(a=>a.teacherId===u.id&&a.subject===subject))return NextResponse.json({error:"No tienes esta asignación docente"},{status:403});
 const ids=Array.isArray(b.objectiveIds)?b.objectiveIds.map(String):[];const moduleId=String(b.moduleId||"").trim();const objectives=moduleId?await prisma.learningObjective.findMany({where:{id:{in:ids},moduleLinks:{some:{moduleId,module:{active:true}}}}}):await prisma.learningObjective.findMany({where:{id:{in:ids},level:course.level,subject}});if(!objectives.length)return NextResponse.json({error:"Selecciona al menos un OA oficial"},{status:400});if(moduleId){const module=await prisma.curriculumModule.findFirst({where:{id:moduleId,active:true}});if(!module)return NextResponse.json({error:"Módulo TP oficial no encontrado"},{status:400});}
 const type=String(b.type||"SUMMATIVE");if(!["DIAGNOSTIC","FORMATIVE","SUMMATIVE"].includes(type))return NextResponse.json({error:"Tipo de evaluación no válido"},{status:400});
 const instrument=String(b.instrument||"Prueba mixta");const instrumentGuidance:Record<string,string>={"Rúbrica":"Genera criterios observables, 4 niveles de desempeño con descriptores claros por criterio, puntaje por nivel y puntaje total.","Pauta de observación":"Genera indicadores observables, escala de apreciación, espacio para evidencia/observaciones y criterios de interpretación.","Lista de cotejo":"Genera indicadores verificables alineados a los OA, columnas Sí, No y No observado, más observaciones.","Autoevaluación":"Genera criterios comprensibles para estudiantes, escala de valoración, preguntas de reflexión, fortalezas y compromisos de mejora.","Coevaluación":"Genera criterios claros para evaluación entre pares, escala de valoración, evidencia, retroalimentación respetuosa y compromiso de mejora."};const generationMode=b.generationMode==="TEACHER"?"TEACHER":"AI";const itemComposition=Array.isArray(b.itemComposition)?b.itemComposition.filter((x:any)=>String(x.type||"").trim()&&Number(x.count)>0).map((x:any)=>({type:String(x.type),count:Math.max(1,Math.min(60,Number(x.count)||1))})):[];const questions=Math.max(1,Math.min(60,Number(b.questions)||20));const duration=String(b.duration||"60 minutos");const instructions=String(b.instructions||"");const totalScore=type==="SUMMATIVE"?Math.max(1,Number(b.totalScore)||questions):undefined;const difficulty=type==="SUMMATIVE"?Math.max(1,Math.min(100,Number(b.difficulty)||60)):undefined;const itemScores=type==="SUMMATIVE"&&Array.isArray(b.itemScores)?b.itemScores.map((x:any)=>Math.max(0,Number(x)||0)).slice(0,questions):[];if(type==="SUMMATIVE"&&itemScores.length===questions&&Math.abs(itemScores.reduce((a:number,v:number)=>a+v,0)-(totalScore||0))>0.001)return NextResponse.json({error:"La suma de puntajes por ítem debe coincidir con el puntaje total"},{status:400});const passingScore=type==="SUMMATIVE"?Number(((totalScore||0)*(difficulty||0)/100).toFixed(2)):undefined;
 const instrumentInstruction=instrumentGuidance[instrument]||"Genera el instrumento solicitado con instrucciones, ítems, puntajes y pauta cuando corresponda.";const compositionText=generationMode==="TEACHER"?`ESTRUCTURA OBLIGATORIA DEL DOCENTE: ${itemComposition.map((x:any)=>`${x.count} ítems de ${x.type}`).join("; ")}. Debes respetar exactamente esta composición y producir exactamente ${questions} ítems.`:`La IA puede proponer la combinación de ítems, pero debe producir exactamente ${questions} ítems.`;const scoreText=type==="SUMMATIVE"?`CONFIGURACIÓN SUMATIVA OBLIGATORIA: puntaje total ${totalScore}; exigencia ${difficulty}%; puntaje mínimo de aprobación ${passingScore}; ${itemScores.length===questions?`puntajes exactos por ítem en orden: ${itemScores.join(", ")}`:"distribuye los puntajes de modo que sumen exactamente el puntaje total"}.`:"";const prompt=`Genera una evaluación escolar chilena en español. Curso: ${course.name}. Asignatura: ${subject}. Tipo: ${type}. Instrumento: ${instrument}. ${instrumentInstruction} ${compositionText} ${scoreText} Duración: ${duration}. OA oficiales, que no debes inventar ni modificar: ${objectives.map(o=>o.code+": "+o.text).join(" | ")}. Indicaciones del docente: ${instructions||"ninguna"}. Devuelve SOLO JSON válido con: titulo, instrucciones, puntajeTotal, instrumento, criterios, escala, tablaEspecificaciones (array de objetos con oa, habilidad, items, puntaje), items (array de objetos con numero,tipo,enunciado,alternativas array,respuestaCorrecta,puntaje,oa), pautaCorreccion, nivelesLogro (array de objetos con nivel,desde,hasta,descripcion), configuracionSumativa (objeto con puntajeTotal,porcentajeExigencia,puntajeAprobacion), observaciones. Asegura trazabilidad OA y respeta todos los parámetros definidos por el docente.`;
 const ai=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Authorization":`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5.6-terra",input:prompt})});const raw=await ai.json();if(!ai.ok)return NextResponse.json({error:"La IA no pudo generar la evaluación",detail:raw?.error?.message||"Error OpenAI"},{status:502});
 let text=outputText(raw).trim().replace(/^\`\`\`json\s*/i,"").replace(/\`\`\`$/,"").trim();let generated:any;try{generated=JSON.parse(text)}catch{return NextResponse.json({error:"La IA respondió en un formato no válido. Intenta nuevamente."},{status:502})}
 const assessment=await prisma.assessment.create({data:{title:String(generated.titulo||`Evaluación ${subject} · ${course.name}`),type:type as any,track:course.track,content:generated,userId:u.id,courseId:course.id,academicYearId:course.academicYearId,objectives:{create:objectives.map(o=>({objectiveId:o.id}))}},include:{course:true,objectives:{include:{objective:true}},result:true}});await chargeAiUse(u.id);return NextResponse.json({assessment},{status:201});
}
export async function PATCH(req:Request){
 const u=await currentUser();if(!u)return NextResponse.json({error:"No autorizado"},{status:401});
 const b=await req.json();const assessment=await prisma.assessment.findUnique({where:{id:String(b.id||"")},include:{course:true}});
 if(!assessment)return NextResponse.json({error:"Evaluación no encontrada"},{status:404});
 if(u.role==="DOCENTE"&&assessment.userId!==u.id)return NextResponse.json({error:"No autorizado"},{status:403});
 if(u.role==="SOSTENEDOR"){const school=await prisma.school.findUnique({where:{id:assessment.course.schoolId},select:{organizationId:true}});if(school?.organizationId!==u.organizationId)return NextResponse.json({error:"No autorizado"},{status:403})}else if(u.role!=="SUPERADMIN"&&(!u.schoolId||assessment.course.schoolId!==u.schoolId))return NextResponse.json({error:"No autorizado"},{status:403});
 if(!b.content||typeof b.content!=="object")return NextResponse.json({error:"Contenido no válido"},{status:400});
 const updated=await prisma.assessment.update({where:{id:assessment.id},data:{title:String(b.title||assessment.title),content:b.content}});
 return NextResponse.json({assessment:updated});
}