export type HCOffering={name:string;area:string;weeklyHours:number;source:"MINEDUC"};
export const hcDifferentiatedCatalog:HCOffering[]=[
{name:"Artes visuales, audiovisuales y multimediales",area:"Artes",weeklyHours:6,source:"MINEDUC"},
{name:"Creación y composición musical",area:"Artes",weeklyHours:6,source:"MINEDUC"},
{name:"Interpretación musical",area:"Artes",weeklyHours:6,source:"MINEDUC"},
{name:"Interpretación y creación en danza",area:"Artes",weeklyHours:6,source:"MINEDUC"},
{name:"Interpretación y creación en teatro",area:"Artes",weeklyHours:6,source:"MINEDUC"},
{name:"Diseño y arquitectura",area:"Artes",weeklyHours:6,source:"MINEDUC"},
{name:"Biología de los ecosistemas",area:"Ciencias",weeklyHours:6,source:"MINEDUC"},
{name:"Biología celular y molecular",area:"Ciencias",weeklyHours:6,source:"MINEDUC"},
{name:"Ciencias de la salud",area:"Ciencias",weeklyHours:6,source:"MINEDUC"},
{name:"Física",area:"Ciencias",weeklyHours:6,source:"MINEDUC"},
{name:"Química",area:"Ciencias",weeklyHours:6,source:"MINEDUC"},
{name:"Promoción de estilos de vida activos y saludables",area:"Educación Física y Salud",weeklyHours:6,source:"MINEDUC"},
{name:"Ciencias del ejercicio físico y deportivo",area:"Educación Física y Salud",weeklyHours:6,source:"MINEDUC"},
{name:"Expresión corporal",area:"Educación Física y Salud",weeklyHours:6,source:"MINEDUC"},
{name:"Estética",area:"Filosofía",weeklyHours:6,source:"MINEDUC"},
{name:"Filosofía política",area:"Filosofía",weeklyHours:6,source:"MINEDUC"},
{name:"Seminario de filosofía",area:"Filosofía",weeklyHours:6,source:"MINEDUC"},
{name:"Comprensión histórica del presente",area:"Historia, Geografía y Ciencias Sociales",weeklyHours:6,source:"MINEDUC"},
{name:"Geografía, territorio y desafíos socioambientales",area:"Historia, Geografía y Ciencias Sociales",weeklyHours:6,source:"MINEDUC"},
{name:"Economía y sociedad",area:"Historia, Geografía y Ciencias Sociales",weeklyHours:6,source:"MINEDUC"},
{name:"Taller de literatura",area:"Lengua y Literatura",weeklyHours:6,source:"MINEDUC"},
{name:"Lectura y escritura especializadas",area:"Lengua y Literatura",weeklyHours:6,source:"MINEDUC"},
{name:"Participación y argumentación en democracia",area:"Lengua y Literatura",weeklyHours:6,source:"MINEDUC"},
{name:"Límites, derivadas e integrales",area:"Matemática",weeklyHours:6,source:"MINEDUC"},
{name:"Probabilidades y estadística descriptiva e inferencial",area:"Matemática",weeklyHours:6,source:"MINEDUC"},
{name:"Pensamiento computacional y programación",area:"Matemática",weeklyHours:6,source:"MINEDUC"},
{name:"Geometría 3D",area:"Matemática",weeklyHours:6,source:"MINEDUC"}
];
