export const OA_CATALOG_SCOPE = {
  source: "Currículum Nacional · MINEDUC",
  sourceUrls: {
    basic1to6: "https://www.curriculumnacional.cl/curriculum/1o-6o-basico",
    basic7to2m: "https://www.curriculumnacional.cl/curriculum/7o-basico-2-medio",
    medio3to4: "https://www.curriculumnacional.cl/curriculum/3o-4o-medio"
  },
  levels: ["1° Básico","2° Básico","3° Básico","4° Básico","5° Básico","6° Básico","7° Básico","8° Básico","1° Medio","2° Medio","3° Medio","4° Medio"],
  catalogPolicy: "Catálogo referencial de OA basado en Currículum Nacional · MINEDUC. Para uso comercial, conservar código, nivel, asignatura y referencia oficial; no reproducir masivamente textos íntegros sin una licencia/autorización compatible. Excluir documentos identificados como propuesta, borrador o consulta pública del catálogo vigente. Inglés 1°-4° (Propuesta) y Religión se gestionan separadamente.",
  licensingNote: "La ficha oficial de Bases Curriculares 7° Básico a 2° Medio informa restricciones de uso comercial. Verificar autorización/licencia antes de persistir o redistribuir textos íntegros de OA en el SaaS.",
  optionalPrograms1to4: ["Inglés (Propuesta)"],
  separatePrograms: ["Religión"],
  catalogStatus: "GENERAL_FORMATION_3_4_MEDIO_LOADED",
  subjects1to4: ["Artes Visuales","Ciencias Naturales","Educación Física y Salud","Historia, Geografía y Ciencias Sociales","Lenguaje y Comunicación","Matemática","Música","Orientación","Tecnología","Lengua y Cultura de los Pueblos Originarios Ancestrales"],
  subjects5to6: ["Artes Visuales","Ciencias Naturales","Educación Física y Salud","Historia, Geografía y Ciencias Sociales","Idioma Extranjero: Inglés","Lenguaje y Comunicación","Matemática","Música","Orientación","Tecnología","Lengua y Cultura de los Pueblos Originarios Ancestrales"],
  subjects7to2m: ["Artes Visuales","Ciencias Naturales","Educación Física y Salud","Historia, Geografía y Ciencias Sociales","Idioma Extranjero: Inglés","Lengua y Literatura","Matemática","Música","Orientación","Tecnología"],
  subjects3to4m: ["Lengua y Literatura","Matemática","Idioma Extranjero: Inglés","Ciencias para la Ciudadanía","Educación Ciudadana","Filosofía"]
} as const;

export function expectedOASubjects(level:string): readonly string[] {
 if(["1° Básico","2° Básico","3° Básico","4° Básico"].includes(level)) return OA_CATALOG_SCOPE.subjects1to4;
 if(["5° Básico","6° Básico"].includes(level)) return OA_CATALOG_SCOPE.subjects5to6;
 if(["7° Básico","8° Básico","1° Medio","2° Medio"].includes(level)) return OA_CATALOG_SCOPE.subjects7to2m;
 if(["3° Medio","4° Medio"].includes(level)) return OA_CATALOG_SCOPE.subjects3to4m;
 return [];
}

export const verifiedOATotals: Record<string,Record<string,number>> = {
 "1° Básico":{
  "Matemática":20,
  "Lenguaje y Comunicación":26,
  "Historia, Geografía y Ciencias Sociales":15,
  "Ciencias Naturales":12,
  "Artes Visuales":5,
  "Música":7,
  "Educación Física y Salud":11,
  "Tecnología":7,
  "Orientación":8
 },
 "2° Básico":{
  "Matemática":22,
  "Lenguaje y Comunicación":30,
  "Ciencias Naturales":14,
  "Historia, Geografía y Ciencias Sociales":16,
  "Artes Visuales":5,
  "Música":7,
  "Educación Física y Salud":11,
  "Tecnología":7,
  "Orientación":8
 },
 "3° Básico":{
  "Matemática":26,
  "Lenguaje y Comunicación":31,
  "Ciencias Naturales":13,
  "Artes Visuales":5,
  "Música":8,
  "Tecnología":7,
  "Historia, Geografía y Ciencias Sociales":16,
  "Educación Física y Salud":11,
  "Orientación":8
 },
 "4° Básico":{
  "Matemática":27,
  "Lenguaje y Comunicación":30,
  "Ciencias Naturales":17,
  "Historia, Geografía y Ciencias Sociales":18,
  "Música":8,
  "Tecnología":7,
  "Artes Visuales":5,
  "Educación Física y Salud":11,
  "Orientación":8
 },
 "5° Básico":{
  "Matemática":24,
  "Lenguaje y Comunicación":30,
  "Ciencias Naturales":14,
  "Historia, Geografía y Ciencias Sociales":22,
  "Artes Visuales":5,
  "Música":8,
  "Educación Física y Salud":11,
  "Tecnología":7,
  "Idioma Extranjero: Inglés":16,
  "Orientación":9
 },
 "6° Básico":{
  "Matemática":24,
  "Lenguaje y Comunicación":31,
  "Ciencias Naturales":18,
  "Historia, Geografía y Ciencias Sociales":26,
  "Idioma Extranjero: Inglés":16,
  "Orientación":9,
  "Música":8,
  "Educación Física y Salud":11,
  "Tecnología":7,
  "Artes Visuales":5
 },
 "7° Básico":{
  "Matemática":19,
  "Lengua y Literatura":25,
  "Ciencias Naturales":15,
  "Historia, Geografía y Ciencias Sociales":23,
  "Artes Visuales":6,
  "Idioma Extranjero: Inglés":16,
  "Música":7,
  "Educación Física y Salud":5,
  "Tecnología":6,
  "Orientación":10
 },
 "8° Básico":{
  "Matemática":17,
  "Lengua y Literatura":26,
  "Ciencias Naturales":15,
  "Historia, Geografía y Ciencias Sociales":22,
  "Artes Visuales":6,
  "Idioma Extranjero: Inglés":16,
  "Música":7,
  "Educación Física y Salud":5,
  "Tecnología":6,
  "Orientación":10
 },
 "1° Medio":{
  "Matemática":15,
  "Lengua y Literatura":24,
  "Ciencias Naturales":20,
  "Historia, Geografía y Ciencias Sociales":22,
  "Idioma Extranjero: Inglés":16,
  "Música":7,
  "Artes Visuales":6,
  "Educación Física y Salud":5,
  "Tecnología":6,
  "Orientación":10
 },
 "3° Medio":{"Matemática":4,"Lengua y Literatura":9,"Idioma Extranjero: Inglés":4,"Ciencias para la Ciudadanía":12,"Educación Ciudadana":8,"Filosofía":6},
 "4° Medio":{"Matemática":4,"Lengua y Literatura":8,"Idioma Extranjero: Inglés":4,"Ciencias para la Ciudadanía":12,"Educación Ciudadana":8,"Filosofía":5},
 "2° Medio":{
  "Matemática":12,
  "Lengua y Literatura":24,
  "Ciencias Naturales":18,
  "Historia, Geografía y Ciencias Sociales":25,
  "Idioma Extranjero: Inglés":16,
  "Artes Visuales":6,
  "Música":7,
  "Educación Física y Salud":5,
  "Tecnología":6,
  "Orientación":10
 }
};
export const variantBasedSubjects = ["Lengua y Cultura de los Pueblos Originarios Ancestrales"] as const;
export function expectedOACount(level:string,subject:string){return verifiedOATotals[level]?.[subject]??null}
export function isVariantBasedOACatalog(subject:string){return variantBasedSubjects.includes(subject as any)}

// Bloques cuyo contenido curricular ha sido efectivamente incorporado al seed maestro.
// verifiedOATotals solo expresa cantidades contrastadas; no implica que el texto del catálogo esté cargado.
export const loadedCatalogBlocks = new Set([
 "1° Básico|Ciencias Naturales",
 "8° Básico|Matemática",
 "8° Básico|Lengua y Literatura",
 "8° Básico|Ciencias Naturales",
 "8° Básico|Historia, Geografía y Ciencias Sociales",
 "8° Básico|Artes Visuales",
 "8° Básico|Música",
 "8° Básico|Educación Física y Salud",
 "8° Básico|Tecnología",
 "8° Básico|Orientación",
 "8° Básico|Idioma Extranjero: Inglés",

 "1° Básico|Matemática",
 "1° Básico|Lenguaje y Comunicación",
 "1° Básico|Historia, Geografía y Ciencias Sociales",
 "1° Básico|Artes Visuales",
 "1° Básico|Música",
 "1° Básico|Educación Física y Salud",
 "1° Básico|Tecnología",
 "1° Básico|Orientación",
 "2° Básico|Matemática",
 "2° Básico|Lenguaje y Comunicación",
 "2° Básico|Ciencias Naturales",
 "2° Básico|Historia, Geografía y Ciencias Sociales",
 "2° Básico|Artes Visuales",
 "2° Básico|Música",
 "2° Básico|Educación Física y Salud",
 "2° Básico|Tecnología",
 "2° Básico|Orientación",
 "3° Básico|Matemática",
 "3° Básico|Lenguaje y Comunicación",
 "3° Básico|Ciencias Naturales",
 "3° Básico|Historia, Geografía y Ciencias Sociales",
 "3° Básico|Artes Visuales",
 "3° Básico|Música",
 "3° Básico|Educación Física y Salud",
 "3° Básico|Tecnología",
 "3° Básico|Orientación",
 "4° Básico|Matemática",
 "4° Básico|Lenguaje y Comunicación",
 "4° Básico|Ciencias Naturales",
 "4° Básico|Historia, Geografía y Ciencias Sociales",
 "4° Básico|Artes Visuales",
 "4° Básico|Música",
 "4° Básico|Educación Física y Salud",
 "4° Básico|Tecnología",
 "4° Básico|Orientación",
 "5° Básico|Matemática",
 "5° Básico|Lenguaje y Comunicación",
 "5° Básico|Ciencias Naturales",
 "5° Básico|Historia, Geografía y Ciencias Sociales",
 "5° Básico|Artes Visuales",
 "5° Básico|Música",
 "5° Básico|Educación Física y Salud",
 "5° Básico|Tecnología",
 "5° Básico|Orientación",
 "5° Básico|Idioma Extranjero: Inglés",
 "6° Básico|Matemática",
 "6° Básico|Lenguaje y Comunicación",
 "6° Básico|Ciencias Naturales",
 "6° Básico|Historia, Geografía y Ciencias Sociales",
 "6° Básico|Artes Visuales",
 "6° Básico|Música",
 "6° Básico|Educación Física y Salud",
 "6° Básico|Tecnología",
 "6° Básico|Orientación",
 "6° Básico|Idioma Extranjero: Inglés",
 "7° Básico|Matemática",
 "7° Básico|Lengua y Literatura",
 "7° Básico|Ciencias Naturales",
 "7° Básico|Historia, Geografía y Ciencias Sociales",
 "7° Básico|Artes Visuales",
 "7° Básico|Idioma Extranjero: Inglés",
 "7° Básico|Música",
 "7° Básico|Educación Física y Salud",
 "7° Básico|Tecnología",
 "7° Básico|Orientación",
 "1° Medio|Matemática",
 "1° Medio|Lengua y Literatura",
 "1° Medio|Ciencias Naturales",
 "1° Medio|Historia, Geografía y Ciencias Sociales",
 "1° Medio|Idioma Extranjero: Inglés",
 "1° Medio|Música",
 "1° Medio|Artes Visuales",
 "1° Medio|Educación Física y Salud",
 "1° Medio|Tecnología",
 "1° Medio|Orientación",
 "2° Medio|Matemática",
 "2° Medio|Lengua y Literatura",
 "2° Medio|Ciencias Naturales",
 "2° Medio|Historia, Geografía y Ciencias Sociales",
 "2° Medio|Idioma Extranjero: Inglés",
 "2° Medio|Artes Visuales",
 "2° Medio|Música",
 "2° Medio|Educación Física y Salud",
 "2° Medio|Tecnología",
 "2° Medio|Orientación",
 "3° Medio|Matemática","3° Medio|Lengua y Literatura","3° Medio|Idioma Extranjero: Inglés","3° Medio|Ciencias para la Ciudadanía","3° Medio|Educación Ciudadana","3° Medio|Filosofía",
 "4° Medio|Matemática","4° Medio|Lengua y Literatura","4° Medio|Idioma Extranjero: Inglés","4° Medio|Ciencias para la Ciudadanía","4° Medio|Educación Ciudadana","4° Medio|Filosofía"]);
export function isCatalogBlockSeeded(level:string,subject:string){return loadedCatalogBlocks.has(level+"|"+subject)}
