export const mecanicaIndustrialMencionesOfficialCatalog=[
{code:"ME-MAEM-M00",name:"Emprendimiento y empleabilidad",level:"4° Medio TP · Mención Mantenimiento Electromecánico",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81972.html",objectives:[]},
{code:"ME-MAEM-M01",name:"Mantenimiento y reparación industrial",level:"4° Medio TP · Mención Mantenimiento Electromecánico",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81973.html",objectives:[{code:"OA 1",text:"Realizar mantenimiento preventivo de la máquina, tanto en funcionamiento como detenida, empleando pautas entregadas por el fabricante y la bitácora de funcionamiento de la máquina, aplicando la normativa de seguridad y de protección del medio ambiente."},{code:"OA 4",text:"Reponer o reparar partes y piezas de equipos, máquinas automáticas y de alta producción, sistemas mecánicos, electromecánicos, hidráulicos y neumáticos de procesos industriales que hayan cumplido su vida útil o que hayan sufrido desgaste o deterioro, de acuerdo al manual del fabricante, respetando las normas de seguridad y de protección del medio ambiente."}]},
{code:"ME-MAEM-M02",name:"Detección de fallas en sistemas industriales",level:"4° Medio TP · Mención Mantenimiento Electromecánico",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81974.html",objectives:[{code:"OA 2",text:"Comprobar el funcionamiento de partes y componentes, detectando problemas eléctricos y mecánicos de equipos, sistemas mecánicos, electromecánicos, hidráulicos y neumáticos de procesos industriales, mediante el uso de instrumentos y el manual del fabricante."}]},
{code:"ME-MAEM-M03",name:"Control de procesos industriales",level:"4° Medio TP · Mención Mantenimiento Electromecánico",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81975.html",objectives:[{code:"OA 3",text:"Instalar componentes, equipos, sistemas eléctricos, electrónicos y automatizados empleados en el control de procesos, utilizando las herramientas, instrumentos y materiales apropiados, considerando los principios y fundamentos de la electricidad, la condición física del lugar, los planos, los elementos de fijación, la conexión y la normativa eléctrica y de seguridad."}]},
{code:"ME-MAEM-M04",name:"Montaje de equipos y sistemas industriales",level:"4° Medio TP · Mención Mantenimiento Electromecánico",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81976.html",objectives:[{code:"OA 5",text:"Poner en funcionamiento equipos, sistemas mecánicos, electromecánicos, hidráulicos y neumáticos de procesos industriales, realizando las mediciones correspondientes con los instrumentos apropiados, comprobando su correcto funcionamiento, de acuerdo a las tablas de tolerancia establecidas por el fabricante y respetando las normas de seguridad y de protección del medio ambiente."}]},
{code:"ME-MAHE-M00",name:"Emprendimiento y empleabilidad",level:"4° Medio TP · Mención Máquinas-Herramientas",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81977.html",objectives:[]},
{code:"ME-MAHE-M01",name:"Torneado de piezas y conjuntos mecánicos",level:"4° Medio TP · Mención Máquinas-Herramientas",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81978.html",objectives:[{code:"OA 1",text:"Fabricar partes y piezas de conjuntos mecánicos con máquinas-herramientas convencionales, de acuerdo al manual del fabricante, las especificaciones técnicas, los principios de la mecanización, las normas de seguridad y de protección del medio ambiente."}]},
{code:"ME-MAHE-M02",name:"Fresado de piezas y conjuntos mecánicos",level:"4° Medio TP · Mención Máquinas-Herramientas",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81979.html",objectives:[{code:"OA 2",text:"Fabricar partes y piezas de conjuntos mecánicos con fresadora universal, de acuerdo a las indicaciones del fabricante, las especificaciones técnicas, los principios de la mecanización con fresa, las normas de seguridad y de protección del medio ambiente."}]},
{code:"ME-MAHE-M03",name:"Taladrado y rectificado de piezas mecánicas",level:"4° Medio TP · Mención Máquinas-Herramientas",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81980.html",objectives:[{code:"OA 3",text:"Utiliza máquinas rectificadoras y taladradoras para la fabricación o reparación de partes y piezas de conjuntos mecánicos, de acuerdo al manual del fabricante, las especificaciones técnicas, los principios de seguridad y de protección del medio ambiente."}]},
{code:"ME-MAHE-M04",name:"Mecanizado con máquinas de control numérico computacional",level:"4° Medio TP · Mención Máquinas-Herramientas",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81981.html",objectives:[{code:"OA 4",text:"Programar y utilizar máquinas de control numérico (CNC)y manufactura asistida por computación CAM) para la fabricación de piezas y partes de conjuntos mecánicos, de acuerdo a los procedimientos establecidos, a las indicaciones del fabricante y a las especificaciones técnicas."},{code:"OA 5",text:"Programar y utilizar centros de mecanizado para la fabricación de piezas y partes de conjuntos mecánicos, de acuerdo a las indicaciones del fabricante y a las especificaciones técnicas."}]},
{code:"ME-MATR-M00",name:"Emprendimiento y empleabilidad",level:"4° Medio TP · Mención Matricería",sourceUrl:"https://www.curriculumnacional.cl/614/w3-propertyvalue-138826.html",objectives:[]},
{code:"ME-MATR-M01",name:"Fabricación de matrices",level:"4° Medio TP · Mención Matricería",sourceUrl:"https://www.curriculumnacional.cl/614/w3-propertyvalue-138826.html",objectives:[{code:"OA 1",text:"Elaborar, montar y desmontar matrices en máquinas y equipos industriales, para la fabricación de piezas de diferentes materiales, de acuerdo a las especificaciones técnicas y a las normas de matricería."}]},
{code:"ME-MATR-M02",name:"Fabricación de moldes",level:"4° Medio TP · Mención Matricería",sourceUrl:"https://www.curriculumnacional.cl/614/w3-propertyvalue-138826.html",objectives:[{code:"OA 2",text:"Elaborar, montar y desmontar moldes de inyección de diversos materiales en máquinas y equipos industriales, de acuerdo a las especificidades del modelo y de la máquina."}]},
{code:"ME-MATR-M03",name:"Mantenimiento de matrices y moldes",level:"4° Medio TP · Mención Matricería",sourceUrl:"https://www.curriculumnacional.cl/614/w3-propertyvalue-138826.html",objectives:[{code:"OA 3",text:"Detectar fallas en matrices y moldes, y controlar la calidad de los procesos, insumos y productos, de acuerdo a las normas y a los parámetros establecidos."},{code:"OA 4",text:"Ejecutar el mantenimiento preventivo y correctivo, y el retocado de matrices, moldes y útiles de matricería, utilizando productos y máquinas, herramientas y máquinasherramientas programadas apropiadas, de acuerdo a las características de los materiales, el modelo y la muestra."},{code:"OA 6",text:"Manipular residuos y desechos de las matrices, aplicando técnicas compatibles con el cuidado del medio ambiente."}]},
{code:"ME-MATR-M04",name:"Diseño y dibujo de moldes y matrices",level:"4° Medio TP · Mención Matricería",sourceUrl:"https://www.curriculumnacional.cl/614/w3-propertyvalue-138826.html",objectives:[{code:"OA 5",text:"Dibujar moldes mediante uso de software de diseño."}]}
] as const;