export const electricidadOfficialCatalog=[
{code:"EL-ETRI-M01",name:"Instalación de motores eléctricos y equipos de calefacción",level:"3° Medio TP",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81886.html",objectives:[{code:"OA 4",text:"Ejecutar instalaciones de calefacción y fuerza motriz en baja tensión, con un máximo de 5 kW de potencia total instalada, sin alimentadores, aplicando la normativa eléctrica vigente, de acuerdo a los planos, a la memoria de cálculo y a los presupuestos con cubicación de materiales y mano de obra."}]},
{code:"EL-ETRI-M02",name:"Instalaciones eléctricas domiciliarias",level:"3° Medio TP",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81887.html",objectives:[{code:"OA 1",text:"Leer y utilizar especificaciones técnicas, planos, diagramas y proyectos de instalación eléctricos."},{code:"OA 3",text:"Ejecutar instalaciones de alumbrado en baja tensión con un máximo de 10 kW de potencia instalada total, sin alimentadores, aplicando la normativa eléctrica vigente, de acuerdo a los planos, a la memoria de cálculo y a los presupuestos con cubicación de materiales y mano de obra."}]},
{code:"EL-ETRI-M03",name:"Elaboración de proyectos eléctricos",level:"3° Medio TP",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81888.html",objectives:[{code:"OA 1",text:"Leer y utilizar especificaciones técnicas, planos, diagramas y proyectos de instalación eléctricos."},{code:"OA 2",text:"Dibujar circuitos eléctricos con software de CAD, en planos de plantas libres, aplicando la normativa eléctrica vigente."},{code:"OA 5",text:"Cubicar materiales e insumos para instalaciones eléctricas de baja tensión de acuerdo a los planos y a las especificaciones técnicas aplicando los principios matemáticos que correspondan."}]},
{code:"EL-ETRI-M04",name:"Mantenimiento de máquinas, equipos y sistemas eléctricos",level:"3° Medio TP",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81889.html",objectives:[{code:"OA 6",text:"Mantener y reemplazar componentes, equipos y sistemas eléctricos monofásicos y trifásicos, utilizando las herramientas, instrumentos e insumos apropiados, considerando las pautas de mantenimiento, los procedimientos, las especificaciones técnicas, las recomendaciones de los fabricantes, la normativa y los estándares de seguridad."}]},
{code:"EL-ETRI-M05",name:"Instalación de sistemas de control eléctrico industrial",level:"4° Medio TP",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81890.html",objectives:[{code:"OA 5",text:"Cubicar materiales e insumos para instalaciones eléctricas de baja tensión, de acuerdo a los planos y a las especificaciones técnicas y aplicando los principios matemáticos que correspondan."},{code:"OA 7",text:"Ejecutar sistemas de control, fuerza y protecciones eléctricas de máquinas, equipos e instalaciones eléctricas, según los requerimientos del proyecto y las especificaciones del fabricante, respetando la normativa eléctrica y del control del medio ambiente vigente."}]},
{code:"EL-ETRI-M06",name:"Instalaciones eléctricas industriales",level:"4° Medio TP",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81891.html",objectives:[{code:"OA 4",text:"Ejecutar instalaciones de calefacción y fuerza motriz en baja tensión, con un máximo de 5 kW de potencia total instalada, sin alimentadores, aplicando la normativa eléctrica vigente, de acuerdo a los planos, a la memoria de cálculo y a los presupuestos con cubicación de materiales y mano de obra."}]},
{code:"EL-ETRI-M07",name:"Instalación de equipos electrónicos de potencia",level:"4° Medio TP",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81892.html",objectives:[{code:"OA 7",text:"Ejecutar sistemas de control, fuerza y protecciones eléctricas de máquinas, equipos e instalaciones eléctricas, según los requerimientos del proyecto y las especificaciones del fabricante, respetando la normativa eléctrica y del control del medio ambiente vigente."}]},
{code:"EL-ETRI-M08",name:"Automatización de sistemas eléctricos industriales",level:"4° Medio TP",sourceUrl:"https://www.curriculumnacional.cl/614/w3-article-81893.html",objectives:[{code:"OA 8",text:"Modificar programas y parámetros en equipos y sistemas eléctricos y electrónicos utilizados en control de procesos, según los requerimientos operacionales del equipo o de la planta y la normativa eléctrica vigente."}]}
] as const;