export const subjectsByLevel: Record<string,string[]> = {
"1° Básico":["Lenguaje y Comunicación","Matemática","Historia, Geografía y Ciencias Sociales","Ciencias Naturales","Artes Visuales","Música","Educación Física y Salud","Tecnología","Orientación","Lengua y Cultura de los Pueblos Originarios Ancestrales","Religión"],
"2° Básico":["Lenguaje y Comunicación","Matemática","Historia, Geografía y Ciencias Sociales","Ciencias Naturales","Artes Visuales","Música","Educación Física y Salud","Tecnología","Orientación","Lengua y Cultura de los Pueblos Originarios Ancestrales","Religión"],
"3° Básico":["Lenguaje y Comunicación","Matemática","Historia, Geografía y Ciencias Sociales","Ciencias Naturales","Artes Visuales","Música","Educación Física y Salud","Tecnología","Orientación","Lengua y Cultura de los Pueblos Originarios Ancestrales","Religión"],
"4° Básico":["Lenguaje y Comunicación","Matemática","Historia, Geografía y Ciencias Sociales","Ciencias Naturales","Artes Visuales","Música","Educación Física y Salud","Tecnología","Orientación","Lengua y Cultura de los Pueblos Originarios Ancestrales","Religión"],
"5° Básico":["Lenguaje y Comunicación","Matemática","Historia, Geografía y Ciencias Sociales","Ciencias Naturales","Idioma Extranjero: Inglés","Artes Visuales","Música","Educación Física y Salud","Tecnología","Orientación","Lengua y Cultura de los Pueblos Originarios Ancestrales","Religión"],
"6° Básico":["Lenguaje y Comunicación","Matemática","Historia, Geografía y Ciencias Sociales","Ciencias Naturales","Idioma Extranjero: Inglés","Artes Visuales","Música","Educación Física y Salud","Tecnología","Orientación","Lengua y Cultura de los Pueblos Originarios Ancestrales","Religión"],
"7° Básico":["Lengua y Literatura","Matemática","Historia, Geografía y Ciencias Sociales","Ciencias Naturales","Idioma Extranjero: Inglés","Artes Visuales","Música","Educación Física y Salud","Tecnología","Orientación","Religión"],
"8° Básico":["Lengua y Literatura","Matemática","Historia, Geografía y Ciencias Sociales","Ciencias Naturales","Idioma Extranjero: Inglés","Artes Visuales","Música","Educación Física y Salud","Tecnología","Orientación","Religión"],
"1° Medio":["Lengua y Literatura","Matemática","Historia, Geografía y Ciencias Sociales","Ciencias Naturales","Idioma Extranjero: Inglés","Artes Visuales","Música","Educación Física y Salud","Tecnología","Orientación","Religión"],
"2° Medio":["Lengua y Literatura","Matemática","Historia, Geografía y Ciencias Sociales","Ciencias Naturales","Idioma Extranjero: Inglés","Artes Visuales","Música","Educación Física y Salud","Tecnología","Orientación","Religión"],
"3° Medio":["Lengua y Literatura","Matemática","Idioma Extranjero: Inglés","Ciencias para la Ciudadanía","Educación Ciudadana","Filosofía","Artes Visuales","Danza","Música","Teatro","Educación Física y Salud 1","Educación Física y Salud 2","Mundo Global","Chile y la Región Latinoamericana","Artes Visuales, Audiovisuales y Multimediales","Creación y Composición Musical","Diseño y Arquitectura","Interpretación Musical","Interpretación y Creación en Danza","Interpretación y Creación en Teatro","Biología Celular y Molecular","Biología de los Ecosistemas","Ciencias de la Salud","Física","Química","Ciencias del Ejercicio Físico y Deportivo","Expresión Corporal","Promoción de Estilos de Vida Activos y Saludables","Comprensión Histórica del Presente","Economía y Sociedad","Geografía, Territorio y Desafíos Socioambientales","Estética","Filosofía Política","Seminario de Filosofía","Geometría 3D","Límites, Derivadas e Integrales","Pensamiento Computacional y Programación","Probabilidades y Estadística Descriptiva e Inferencial","Lectura y Escritura Especializadas","Participación y Argumentación en Democracia","Taller de Literatura","Religión"],
"4° Medio":["Lengua y Literatura","Matemática","Idioma Extranjero: Inglés","Ciencias para la Ciudadanía","Educación Ciudadana","Filosofía","Artes Visuales","Danza","Música","Teatro","Educación Física y Salud 1","Educación Física y Salud 2","Mundo Global","Chile y la Región Latinoamericana","Artes Visuales, Audiovisuales y Multimediales","Creación y Composición Musical","Diseño y Arquitectura","Interpretación Musical","Interpretación y Creación en Danza","Interpretación y Creación en Teatro","Biología Celular y Molecular","Biología de los Ecosistemas","Ciencias de la Salud","Física","Química","Ciencias del Ejercicio Físico y Deportivo","Expresión Corporal","Promoción de Estilos de Vida Activos y Saludables","Comprensión Histórica del Presente","Economía y Sociedad","Geografía, Territorio y Desafíos Socioambientales","Estética","Filosofía Política","Seminario de Filosofía","Geometría 3D","Límites, Derivadas e Integrales","Pensamiento Computacional y Programación","Probabilidades y Estadística Descriptiva e Inferencial","Lectura y Escritura Especializadas","Participación y Argumentación en Democracia","Taller de Literatura","Religión"]
};
export function curricularSubjects(level:string){return subjectsByLevel[level]||[]}


// Asignaturas cuyos OA se sincronizan desde Bases Curriculares MINEDUC.
// Religión se mantiene en la oferta escolar, pero fuera del catálogo OA general porque posee programas/decretos específicos.
export const officialOASubjectsByLevel: Record<string,string[]> = Object.fromEntries(
 Object.entries(subjectsByLevel).map(([level,subjects])=>[level,(level==="3° Medio"||level==="4° Medio")?["Lengua y Literatura","Matemática","Idioma Extranjero: Inglés","Ciencias para la Ciudadanía","Educación Ciudadana","Filosofía","Química","Geometría 3D"]:subjects.filter(subject=>subject!=="Religión")])
);
export function officialOASubjects(level:string){return officialOASubjectsByLevel[level]||[]}
