export const tpCurriculum=[
{specialty:"Electricidad",level:"3° Medio TP",source:"Currículum Nacional · MINEDUC",sourceUrl:"https://www.curriculumnacional.cl/614/w3-propertyvalue-138795.html",objectives:[
["EL OA 1","Leer y utilizar especificaciones técnicas, planos, diagramas y proyectos de instalación eléctricos."],["EL OA 2","Dibujar circuitos eléctricos con software de CAD en planos de plantas libres, aplicando la normativa eléctrica vigente."],["EL OA 3","Ejecutar instalaciones de alumbrado en baja tensión con un máximo de 10 kW de potencia instalada total, sin alimentadores, aplicando la normativa eléctrica vigente, de acuerdo a planos, memoria de cálculo y presupuestos."],["EL OA 4","Ejecutar instalaciones de calefacción y fuerza motriz en baja tensión, con un máximo de 5 kW de potencia total instalada, sin alimentadores, aplicando la normativa eléctrica vigente, de acuerdo a planos, memoria de cálculo y presupuestos."],["EL OA 5","Cubicar materiales e insumos para instalaciones eléctricas de baja tensión, de acuerdo a planos y especificaciones técnicas, aplicando los principios matemáticos correspondientes."],["EL OA 6","Mantener y reemplazar componentes, equipos y sistemas eléctricos monofásicos y trifásicos, utilizando herramientas, instrumentos e insumos apropiados y considerando mantenimiento, procedimientos, especificaciones, normativa y seguridad."],["EL OA 7","Ejecutar sistemas de control, fuerza y protecciones eléctricas de máquinas, equipos e instalaciones según los requerimientos del proyecto y las especificaciones del fabricante, respetando normativa eléctrica y ambiental."],["EL OA 8","Modificar programas y parámetros en equipos y sistemas eléctricos y electrónicos utilizados en control de procesos, según requerimientos operacionales del equipo o planta y normativa eléctrica vigente."]]},
{specialty:"Electricidad",level:"4° Medio TP",source:"Currículum Nacional · MINEDUC",sourceUrl:"https://www.curriculumnacional.cl/614/w3-propertyvalue-138795.html",objectives:[
["EL OA 1","Leer e interpretar especificaciones, planos, diagramas y proyectos eléctricos."],["EL OA 2","Dibujar circuitos eléctricos con software CAD aplicando normativa vigente."],["EL OA 3","Ejecutar instalaciones de alumbrado en baja tensión según planos, cálculos, presupuestos y normativa."],["EL OA 4","Ejecutar instalaciones de calefacción y fuerza motriz en baja tensión según proyecto y normativa."],["EL OA 5","Cubicar materiales e insumos para instalaciones eléctricas de baja tensión."],["EL OA 6","Mantener y reemplazar componentes y sistemas eléctricos monofásicos y trifásicos con seguridad."],["EL OA 7","Ejecutar sistemas de control, fuerza y protecciones eléctricas según proyecto y normativa."],["EL OA 8","Modificar programas y parámetros de equipos eléctricos y electrónicos usados en control de procesos."]]},
{specialty:"Mecánica Industrial",level:"3° Medio TP",source:"Currículum Nacional · MINEDUC",sourceUrl:"https://www.curriculumnacional.cl/614/w3-propertyvalue-138826.html",objectives:[
["MI OA 1","Leer especificaciones técnicas, planos, instrumentos y simbología del trabajo mecánico."],["MI OA 2","Realizar mediciones y controles para fabricación, mantenimiento y reparación mecánica y electromecánica."],["MI OA 3","Unir y reparar elementos mediante corte y soldadura con procedimientos y protección adecuados."],["MI OA 4","Realizar mantenimiento preventivo de herramientas y componentes según pautas del fabricante."],["MI OA 5","Realizar trabajos de sujeción, pulido y ajuste con seguridad y protección ambiental."],["MI OA 6","Aplicar normativa de higiene, seguridad industrial y medioambiental."],["MI OA 7","Aplicar procedimientos y normas de fabricación pertinentes al producto o faena."]]},
{specialty:"Mecánica Industrial - Mención Mantenimiento Electromecánico",level:"4° Medio TP",source:"Currículum Nacional · MINEDUC",sourceUrl:"https://www.curriculumnacional.cl/614/w3-propertyvalue-138826.html",objectives:[
["MI-ME OA 1","Realizar mantenimiento preventivo de máquinas según fabricante, seguridad y protección ambiental."],["MI-ME OA 2","Diagnosticar problemas eléctricos y mecánicos en equipos y sistemas industriales mediante instrumentos y manuales."],["MI-ME OA 3","Instalar componentes y sistemas eléctricos, electrónicos y automatizados de control de procesos."],["MI-ME OA 4","Reponer o reparar partes y piezas de equipos y sistemas industriales deteriorados."],["MI-ME OA 5","Poner en funcionamiento equipos y sistemas industriales verificando parámetros y tolerancias."]]},
{specialty:"Mecánica Industrial - Mención Máquinas-Herramientas",level:"4° Medio TP",source:"Currículum Nacional · MINEDUC",sourceUrl:"https://www.curriculumnacional.cl/614/w3-propertyvalue-138826.html",objectives:[
["MI-MH OA 1","Fabricar piezas con máquinas-herramientas convencionales según especificaciones y seguridad."],["MI-MH OA 2","Fabricar piezas con fresadora universal según especificaciones técnicas."],["MI-MH OA 3","Utilizar rectificadoras y taladradoras para fabricar o reparar piezas mecánicas."],["MI-MH OA 4","Programar y utilizar máquinas CNC y manufactura asistida por computador."],["MI-MH OA 5","Programar y utilizar centros de mecanizado para fabricar piezas mecánicas."]]},
{specialty:"Administración",level:"3° Medio TP",source:"Currículum Nacional · MINEDUC",sourceUrl:"https://www.curriculumnacional.cl/curriculum/3o-4o-medio-tecnico-profesional/especialidad-administracion/3-medio-tp",objectives:[
["ADM OA 1","Leer y utilizar información contable básica acerca de la marcha de la empresa, incluida información sobre importaciones y/o exportaciones, de acuerdo con las normas internacionales de contabilidad e información financiera y la legislación tributaria vigente."],
["ADM OA 2","Elaborar un programa de actividades operativas de un departamento o área de una empresa, de acuerdo con orientaciones de la jefatura y/o del plan estratégico de gestión, considerando recursos humanos, insumos, equipamiento, distribución temporal y proyección de resultados."],
["ADM OA 3","Hacer seguimiento y elaborar informes del desarrollo de un programa operativo de un departamento o área de una empresa, sobre la base de evidencias y técnicas apropiadas, considerando todos los elementos del programa."],
["ADM OA 4","Atender a clientes internos y externos de la empresa de acuerdo con sus necesidades y demandas, aplicando técnicas de relaciones públicas y comunicación oral y escrita, de forma presencial o a distancia."],
["ADM OA 5","Organizar y ordenar el lugar de trabajo de acuerdo con técnicas y procedimientos que permitan disponer y recuperar información u objetos oportunamente para el desarrollo de las tareas."],
["ADM OA 6","Utilizar equipos y herramientas tecnológicas empleadas en la gestión administrativa, considerando el uso eficiente de la energía, los materiales y los insumos."]]},
{specialty:"Administración - Mención Logística",level:"4° Medio TP",source:"Currículum Nacional · MINEDUC",sourceUrl:"https://www.curriculumnacional.cl/curriculum/3o-4o-medio-tecnico-profesional/especialidad-administracion-mencion-logistica/4-medio-tp",objectives:[
["ADM-LOG OA 1","Controlar la entrada y salida de productos, revisando el stock disponible y confirmando la recepción y despacho de forma computacional y/o manual, utilizando instrumentos de registro apropiados y la normativa vigente."],
["ADM-LOG OA 2","Controlar las operaciones de almacenamiento y manejo de existencias de acuerdo con métodos establecidos, detectando el estado cualitativo y cuantitativo de los productos y asignando ubicaciones y sistemas de localización inmediata, manuales y digitales."],
["ADM-LOG OA 3","Cubicar productos, materiales e insumos que requieren almacenaje y los espacios de bodegaje, para lograr una disposición eficiente de los productos y optimizar los espacios."],
["ADM-LOG OA 4","Informar y comunicar datos de almacenaje y de entrada y salida de productos mediante diversos sistemas, como radiofrecuencia y computación."],
["ADM-LOG OA 5","Prevenir riesgos de accidentes laborales aplicando normas básicas de seguridad en zonas de almacenamiento y distribución y reconociendo la rotulación internacional de sustancias peligrosas."]]},
{specialty:"Administración - Mención Recursos Humanos",level:"4° Medio TP",source:"Currículum Nacional · MINEDUC",sourceUrl:"https://www.curriculumnacional.cl/curriculum/3o-4o-medio-tecnico-profesional/especialidad-administracion-mencion-recursos-humanos/4-medio-tp",objectives:[
["ADM-RRHH OA 1","Realizar llenado y tramitación de contratos de trabajo, remuneraciones y finiquitos, de acuerdo con la legislación vigente y las normas internacionales de contabilidad."],
["ADM-RRHH OA 2","Calcular remuneraciones y finiquitos, obligaciones tributarias y previsionales del personal de una empresa, de acuerdo con los contratos de trabajo, la legislación vigente y las normas internacionales de contabilidad."],
["ADM-RRHH OA 3","Ingresar, archivar y presentar información sobre bienestar y desarrollo de personas, ascensos, promociones, transferencias, capacitación, desempeños y evaluaciones, entre otros, para la toma de decisiones de las jefaturas."],
["ADM-RRHH OA 4","Ejecutar tareas sistemáticas de descripción de cargos, reclutamiento y selección de personal, de acuerdo con las necesidades de una empresa, los procedimientos establecidos y la normativa vigente."]]}

];