export const tpCurriculum=[
{specialty:"Electricidad",level:"3° Medio TP",source:"Currículum Nacional · MINEDUC",sourceUrl:"https://www.curriculumnacional.cl/614/w3-propertyvalue-138795.html",objectives:[
["EL OA 1","Leer e interpretar especificaciones, planos, diagramas y proyectos eléctricos."],["EL OA 2","Dibujar circuitos eléctricos con software CAD aplicando normativa vigente."],["EL OA 3","Ejecutar instalaciones de alumbrado en baja tensión según planos, cálculos, presupuestos y normativa."],["EL OA 4","Ejecutar instalaciones de calefacción y fuerza motriz en baja tensión según proyecto y normativa."],["EL OA 5","Cubicar materiales e insumos para instalaciones eléctricas de baja tensión."],["EL OA 6","Mantener y reemplazar componentes y sistemas eléctricos monofásicos y trifásicos con seguridad."],["EL OA 7","Ejecutar sistemas de control, fuerza y protecciones eléctricas según proyecto y normativa."],["EL OA 8","Modificar programas y parámetros de equipos eléctricos y electrónicos usados en control de procesos."]]},
{specialty:"Electricidad",level:"4° Medio TP",source:"Currículum Nacional · MINEDUC",sourceUrl:"https://www.curriculumnacional.cl/614/w3-propertyvalue-138795.html",objectives:[
["EL OA 1","Leer e interpretar especificaciones, planos, diagramas y proyectos eléctricos."],["EL OA 2","Dibujar circuitos eléctricos con software CAD aplicando normativa vigente."],["EL OA 3","Ejecutar instalaciones de alumbrado en baja tensión según planos, cálculos, presupuestos y normativa."],["EL OA 4","Ejecutar instalaciones de calefacción y fuerza motriz en baja tensión según proyecto y normativa."],["EL OA 5","Cubicar materiales e insumos para instalaciones eléctricas de baja tensión."],["EL OA 6","Mantener y reemplazar componentes y sistemas eléctricos monofásicos y trifásicos con seguridad."],["EL OA 7","Ejecutar sistemas de control, fuerza y protecciones eléctricas según proyecto y normativa."],["EL OA 8","Modificar programas y parámetros de equipos eléctricos y electrónicos usados en control de procesos."]]},
{specialty:"Mecánica Industrial",level:"3° Medio TP",source:"Currículum Nacional · MINEDUC",sourceUrl:"https://www.curriculumnacional.cl/614/w3-propertyvalue-138826.html",objectives:[
["MI OA 1","Leer especificaciones técnicas, planos, instrumentos y simbología del trabajo mecánico."],["MI OA 2","Realizar mediciones y controles para fabricación, mantenimiento y reparación mecánica y electromecánica."],["MI OA 3","Unir y reparar elementos mediante corte y soldadura con procedimientos y protección adecuados."],["MI OA 4","Realizar mantenimiento preventivo de herramientas y componentes según pautas del fabricante."],["MI OA 5","Realizar trabajos de sujeción, pulido y ajuste con seguridad y protección ambiental."],["MI OA 6","Aplicar normativa de higiene, seguridad industrial y medioambiental."],["MI OA 7","Aplicar procedimientos y normas de fabricación pertinentes al producto o faena."]]},
{specialty:"Mecánica Industrial",level:"4° Medio TP",source:"Currículum Nacional · MINEDUC",sourceUrl:"https://www.curriculumnacional.cl/614/w3-propertyvalue-138826.html",objectives:[
["MI-ME OA 1","Realizar mantenimiento preventivo de máquinas según fabricante, seguridad y protección ambiental."],["MI-ME OA 2","Diagnosticar problemas eléctricos y mecánicos en equipos y sistemas industriales mediante instrumentos y manuales."],["MI-ME OA 3","Instalar componentes y sistemas eléctricos, electrónicos y automatizados de control de procesos."],["MI-ME OA 4","Reponer o reparar partes y piezas de equipos y sistemas industriales deteriorados."],["MI-ME OA 5","Poner en funcionamiento equipos y sistemas industriales verificando parámetros y tolerancias."],["MI-MH OA 1","Fabricar piezas con máquinas-herramientas convencionales según especificaciones y seguridad."],["MI-MH OA 2","Fabricar piezas con fresadora universal según especificaciones técnicas."],["MI-MH OA 3","Utilizar rectificadoras y taladradoras para fabricar o reparar piezas mecánicas."],["MI-MH OA 4","Programar y utilizar máquinas CNC y manufactura asistida por computador."],["MI-MH OA 5","Programar y utilizar centros de mecanizado para fabricar piezas mecánicas."]]}
];