import {NextResponse} from "next/server";
import {prisma} from "../../../lib/prisma";
import {getSession} from "../../../lib/auth";
import {hcDifferentiatedCatalog} from "../../../lib/hc-curriculum";
async function ctx(){const s=await getSession();if(!s?.id)return null;return prisma.user.findUnique({where:{id:String(s.id)},select:{id:true,role:true,active:true,organizationId:true,schoolId:true}})}
async function scope(u:any,requested?:string|null){const schoolId=u.role==="DIRECTOR"||u.role==="UTP"?u.schoolId:requested||u.schoolId;if(!schoolId)return null;const school=await prisma.school.findFirst({where:{id:schoolId,...(u.role==="SUPERADMIN"?{}:{organizationId:u.organizationId})}});return school?schoolId:null}
export async function GET(req:Request){const u=await ctx();if(!u?.active)return NextResponse.json({error:"No autorizado"},{status:401});const url=new URL(req.url);const schoolId=await scope(u,url.searchParams.get("schoolId"));if(!schoolId)return NextResponse.json({error:"Establecimiento no autorizado"},{status:403});const year=Number(url.searchParams.get("year")||2027);const level=url.searchParams.get("level")||"3° Medio";const ay=await prisma.academicYear.upsert({where:{schoolId_year:{schoolId,year}},update:{},create:{schoolId,year}});const offerings=await prisma.hCCurricularOffering.findMany({where:{academicYearId:ay.id,level},orderBy:[{source:"asc"},{area:"asc"},{name:"asc"}]});return NextResponse.json({catalog:hcDifferentiatedCatalog,offerings,academicYear:ay})}
export async function POST(req:Request){const u=await ctx();if(!u?.active||!["SUPERADMIN","SOSTENEDOR","DIRECTOR","UTP"].includes(u.role))return NextResponse.json({error:"No autorizado"},{status:401});const b=await req.json();const schoolId=await scope(u,b.schoolId);if(!schoolId)return NextResponse.json({error:"Establecimiento no autorizado"},{status:403});const year=Number(b.year||2027),level=String(b.level||"");if(!["3° Medio","4° Medio"].includes(level))return NextResponse.json({error:"Nivel HC no válido"},{status:400});const ay=await prisma.academicYear.upsert({where:{schoolId_year:{schoolId,year}},update:{},create:{schoolId,year}});let name=String(b.name||"").trim(),area=String(b.area||"").trim()||null,weeklyHours:number|null=null,source:"MINEDUC"|"INSTITUTIONAL"=b.source==="INSTITUTIONAL"?"INSTITUTIONAL":"MINEDUC";if(source==="MINEDUC"){const official=hcDifferentiatedCatalog.find(x=>x.name===name);if(!official)return NextResponse.json({error:"Asignatura no pertenece al catálogo oficial"},{status:400});area=official.area;weeklyHours=official.weeklyHours}else{if(!name)return NextResponse.json({error:"Nombre requerido"},{status:400});weeklyHours=Number.isFinite(Number(b.weeklyHours))?Number(b.weeklyHours):null}try{const offering=await prisma.hCCurricularOffering.create({data:{name,area,level,source,weeklyHours,academicYearId:ay.id}});return NextResponse.json(offering,{status:201})}catch{return NextResponse.json({error:"La oferta ya está configurada para este nivel"},{status:409})}}
export async function DELETE(req:Request){const u=await ctx();if(!u?.active||!["SUPERADMIN","SOSTENEDOR","DIRECTOR","UTP"].includes(u.role))return NextResponse.json({error:"No autorizado"},{status:401});const b=await req.json();const o=await prisma.hCCurricularOffering.findUnique({where:{id:String(b.id)},include:{academicYear:true}});if(!o)return NextResponse.json({error:"Oferta no encontrada"},{status:404});const schoolId=await scope(u,o.academicYear.schoolId);if(!schoolId||schoolId!==o.academicYear.schoolId)return NextResponse.json({error:"No autorizado"},{status:403});await prisma.hCCurricularOffering.delete({where:{id:o.id}});return NextResponse.json({ok:true})}
