import {NextResponse} from "next/server";import {prisma} from "../../../lib/prisma";import {getSession} from "../../../lib/auth";
async function user(){const s=await getSession();if(!s?.id)return null;return prisma.user.findUnique({where:{id:String(s.id)},select:{id:true,role:true,active:true,schoolId:true,organizationId:true}})}
const whereFor=(u:any)=>u.role==="DOCENTE"?{userId:u.id}:u.role==="DIRECTOR"||u.role==="UTP"?{course:{schoolId:u.schoolId}}:u.role==="SOSTENEDOR"?{course:{school:{organizationId:u.organizationId}}}:{};
const courseSelect={id:true,name:true,level:true};
const userSelect={id:true,name:true};
export async function GET(req:Request){const u=await user();if(!u?.active)return NextResponse.json({error:"No autorizado"},{status:401});const where:any=whereFor(u);const url=new URL(req.url);const id=url.searchParams.get("id");const kind=url.searchParams.get("kind");
 if(id&&kind){let doc:any=null;if(kind==="planning")doc=await prisma.planning.findFirst({where:{...where,id},include:{course:true,user:{select:userSelect},objectives:{include:{objective:true}},implementation:true}});else if(kind==="assessment")doc=await prisma.assessment.findFirst({where:{...where,id},include:{course:true,user:{select:userSelect},objectives:{include:{objective:true}},result:true}});else if(kind==="material")doc=await prisma.supportMaterial.findFirst({where:{...where,id},include:{course:true,user:{select:userSelect}}});if(!doc)return NextResponse.json({error:"Documento no encontrado"},{status:404});return NextResponse.json({document:doc},{headers:{"Cache-Control":"private, no-store"}});}
 const [plannings,assessments,supportMaterials]=await Promise.all([
 prisma.planning.findMany({where,select:{id:true,title:true,courseId:true,createdAt:true,updatedAt:true,content:true,course:{select:courseSelect},user:{select:userSelect},objectives:{select:{objectiveId:true,objective:{select:{id:true,code:true}}}},implementation:{select:{id:true}}},orderBy:{createdAt:"desc"}}),
 prisma.assessment.findMany({where,select:{id:true,title:true,type:true,courseId:true,createdAt:true,content:true,course:{select:courseSelect},user:{select:userSelect},objectives:{select:{objectiveId:true,objective:{select:{id:true,code:true}}}},result:{select:{id:true}}},orderBy:{createdAt:"desc"}}),
 prisma.supportMaterial.findMany({where,select:{id:true,title:true,materialType:true,subject:true,topic:true,courseId:true,createdAt:true,updatedAt:true,content:true,course:{select:courseSelect},user:{select:userSelect}},orderBy:{createdAt:"desc"}})
 ]);
 const slim=(x:any)=>({...x,content:x.content?.sourcePlanningId?{sourcePlanningId:x.content.sourcePlanningId}:{}});
 return NextResponse.json({plannings:plannings.map(slim),assessments:assessments.map(slim),supportMaterials:supportMaterials.map(slim)},{headers:{"Cache-Control":"private, no-store"}});
}